import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/toastprovider/ToastProvider";
import Navbar from "@/components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>

          <Navbar />

          {children}

          <footer className="mt-4 justify-center align-middle gap-2">
            <hr/>
            <p>Demo: Knowledge Base implementation using Amazon Bedrock and Amazon OpenSearch Serverless</p>
          </footer>

        </ToastProvider>
      </body>
    </html>
  );
}
